//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public long creditcardId { get; set; }
        public long userId { get; set; }
        public string tipo { get; set; }
        public long number { get; set; }
        public byte verifyCode { get; set; }
        public System.DateTime expDate { get; set; }
        public bool isFav { get; set; }
    
        public virtual User User { get; set; }
    }
}
