//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public long orderItemId { get; set; }
        public long productId { get; set; }
        public long orderId { get; set; }
        public int units { get; set; }
        public double unitPrice { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_OrderItemOrderId
        /// </summary>
        public virtual Order Order { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_OrderItemProductId
        /// </summary>
        public virtual Product Product { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + productId.GetHashCode();
    			hash = hash * multiplier + orderId.GetHashCode();
    			hash = hash * multiplier + units.GetHashCode();
    			hash = hash * multiplier + unitPrice.GetHashCode();
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type? 
    
            OrderItem target = obj as OrderItem;
    
    		return true
               &&  (this.orderItemId == target.orderItemId )       
               &&  (this.productId == target.productId )       
               &&  (this.orderId == target.orderId )       
               &&  (this.units == target.units )       
               &&  (this.unitPrice == target.unitPrice )       
               ;
    
        }
    
    
    	public static bool operator ==(OrderItem  objA, OrderItem  objB)
        {
            // Check if the objets are the same OrderItem entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(OrderItem  objA, OrderItem  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strOrderItem = new StringBuilder();
    
    		strOrderItem.Append("[ ");
           strOrderItem.Append(" orderItemId = " + orderItemId + " | " );       
           strOrderItem.Append(" productId = " + productId + " | " );       
           strOrderItem.Append(" orderId = " + orderId + " | " );       
           strOrderItem.Append(" units = " + units + " | " );       
           strOrderItem.Append(" unitPrice = " + unitPrice + " | " );       
            strOrderItem.Append("] ");    
    
    		return strOrderItem.ToString();
        }
    
    
    }
}
