//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ECommerce_Master {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ECommerce_Master() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Es.Udc.DotNet.PracticaMaD.Web.App_LocalResources.ECommerce.Master", typeof(ECommerce_Master).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -.
        /// </summary>
        internal static string lblDash1Resource1_Text {
            get {
                return ResourceManager.GetString("lblDash1Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string lblDash1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("lblDash1Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -.
        /// </summary>
        internal static string lblDash2Resource1_Text {
            get {
                return ResourceManager.GetString("lblDash2Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string lblDash2Resource1_ToolTip {
            get {
                return ResourceManager.GetString("lblDash2Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -.
        /// </summary>
        internal static string lblDash3Resource1_Text {
            get {
                return ResourceManager.GetString("lblDash3Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string lblDash3Resource1_ToolTip {
            get {
                return ResourceManager.GetString("lblDash3Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome!.
        /// </summary>
        internal static string lblWelcome_Hello_Text {
            get {
                return ResourceManager.GetString("lblWelcome.Hello.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to ECommerce.
        /// </summary>
        internal static string lblWelcome_Text {
            get {
                return ResourceManager.GetString("lblWelcome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copyright &amp;copy; Computer Science Department - Univesity of A Coruña.
        /// </summary>
        internal static string lclFooter_Text {
            get {
                return ResourceManager.GetString("lclFooter.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MiniBank: A Sample Model-View-Controller Application with .NET.
        /// </summary>
        internal static string lclHeader_Text {
            get {
                return ResourceManager.GetString("lclHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ECommerce: A MVC Web Application with .NET.
        /// </summary>
        internal static string lclPageTitle_Text {
            get {
                return ResourceManager.GetString("lclPageTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authentication.
        /// </summary>
        internal static string lnkAuthenticate_Text {
            get {
                return ResourceManager.GetString("lnkAuthenticate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string lnkHome_Text {
            get {
                return ResourceManager.GetString("lnkHome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string lnkHome_ToolTip {
            get {
                return ResourceManager.GetString("lnkHome.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Locale.
        /// </summary>
        internal static string lnkLocale_Text {
            get {
                return ResourceManager.GetString("lnkLocale.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        internal static string lnkLogout_Text {
            get {
                return ResourceManager.GetString("lnkLogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string lnkLogout_ToolTip {
            get {
                return ResourceManager.GetString("lnkLogout.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string lnkSearch_Text {
            get {
                return ResourceManager.GetString("lnkSearch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        internal static string lnkUpdate_Text {
            get {
                return ResourceManager.GetString("lnkUpdate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string lnkUpdate_ToolTip {
            get {
                return ResourceManager.GetString("lnkUpdate.ToolTip", resourceCulture);
            }
        }
    }
}
