//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string addLink {
            get {
                return ResourceManager.GetString("addLink", resourceCulture);
=======
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string editButton {
            get {
                return ResourceManager.GetString("editButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expiration Date.
        /// </summary>
        internal static string expDate {
            get {
                return ResourceManager.GetString("expDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Favorite.
        /// </summary>
        internal static string isFav {
            get {
                return ResourceManager.GetString("isFav", resourceCulture);
>>>>>>> 65fe06376c745268ab3f0a5288477b774ba2a24a
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mandatory Field.
        /// </summary>
        internal static string mandatoryField {
            get {
                return ResourceManager.GetString("mandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
=======
        ///   Busca una cadena traducida similar a Number.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
>>>>>>> 65fe06376c745268ab3f0a5288477b774ba2a24a
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca una cadena traducida similar a Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
=======
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        internal static string removeButton {
            get {
                return ResourceManager.GetString("removeButton", resourceCulture);
>>>>>>> 65fe06376c745268ab3f0a5288477b774ba2a24a
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string searchButton {
            get {
                return ResourceManager.GetString("searchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify Code.
        /// </summary>
        internal static string verifyCode {
            get {
                return ResourceManager.GetString("verifyCode", resourceCulture);
            }
        }
    }
}
